version: '3'

services:
  todo_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_service
    env_file: .env
    expose:
      - '8080'
    ports:
      - 8080:8080
    depends_on:
      - todo_mongodb
    volumes:
      - .:/usr/src/todo

  todo_mongodb:
    container_name: "todo_db_container"
    image: mongo:latest
    command: mongod
    environment:
      - MONGO_INITDB_DATABASE=todo
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always
    volumes:
      - todo_mongodb:/data/db
    ports:
      - '27017:27017'

volumes:
    todo_mongodb: {}
